### ISSUE TITLE
How can I find this paper?

### ISSUE THREAD

**Issue by Zoehanlu** [tangrizzly/Point-of-Interest-Recommendation#1]
How can I find this paper《Distance2Pre: Q Cui, Y Tang, S Wu, L Wang. "Distance2Pre: Predict the Next Point-of-Interest via Mining Personalized Spatial Preference". 2019.》?

**Comment by tangrizzly** [comment]
It was accepted but not published online yet.

**Comment by tangrizzly** [comment]
http://shuwu.name/sw/Distance2Pre.pdf
