### ISSUE TITLE
Can not find a file

### ISSUE THREAD

**Issue by jianghusanren007** [tangrizzly/Point-of-Interest-Recommendation#3]
Excuse me. I always got a tip  such as  FileNotFoundError : [ Error 2 ] File b ` ./poidata/Foursquare/sequence/Foursquare.txt `  dose not  exist: b ` ./poidata/Foursquare/sequence/Foursquare.txt `   recently when i running the code of prog_bpr_gru_spatial.py. I guess its maybe miss file that mentioned above.  I hope you can spend a few minutes browsing this question, I would greatil appreciate.

**Comment by tangrizzly** [comment]
I think you probably miss the step to preprocess the dataset first. Please refer to the Usage Section in README.md
